nodejs: 12.19.0 -> 12.19.1
openembedded/meta-openembedded pull request #301
Opened 2020-12-14 22:10 UTC by viatsk

Uprev nodejs in order to fix CVE-2020-8277.
This CVE allows an attacker to trigger a DNS request for a host
of their choice, which could trigger a Denial of Service in
nodejs versions < 12.19.1.

See https://nvd.nist.gov/vuln/detail/CVE-2020-8277 for details.

CVE: CVE-2020-8277
Signed-off-by: Stacy Gaikovaia <Stacy.Gaikovaia@windriver.com>

2020-12-14 22:22 UTC, kraj requested changes
please delete the 12.19.0 recipes as well.

2020-12-17 16:43 UTC, viatsk commented
I've removed the old recipe

2020-12-19 01:15 UTC, kraj approved these changes

2020-12-19 01:15 UTC, kraj commented
its now merged a440154082

2020-12-19 01:15 UTC, closed without merging