ufw: fix python shebang
openembedded/meta-openembedded pull request #344
Opened 2021-04-23 14:30 UTC by Silcet

[meta-openembedded ticket #327] --
https://github.com/openembedded/meta-openembedded/issues/327

The python version in the shebang at the begining of the ufw script
should be the same one as the version the setup.py script was called
with.

The fix in patch "setup-only-make-one-reference-to-env.patch"
depends on sys.executable returning "/usr/bin/env pythonX". However,
it returns "/usr/bin/pythonX". Using sys.version_info we can get the
major version of the python used to called the script and append
that to the shebang line so it works as intended.

Signed-off-by: Silcet <camorga1@gmail.com>

2021-04-23 15:51 UTC, kraj requested changes
this needs to be added to `SRC_URI` as well :)

2021-04-24 15:04 UTC, Silcet commented
I'm a rookie so I made a rookie mistake :) . Fixed now.

2021-04-24 15:07 UTC, Silcet commented
Also, will this be backported or should I make a new PR for dunfell?

2021-04-24 16:24 UTC, kraj commented
once merged into master, backport that into dunfell and create a new pull

2021-04-24 16:24 UTC, kraj reviewed
squash it into single commit.

2021-04-24 16:49 UTC, Silcet commented
Done. Sorry for the mistakes. First time contributing to a big project :)

2021-04-24 17:48 UTC, kraj commented
Fails to build see

https://autobuilder.yoctoproject.org/typhoon/#/builders/88/builds/1170

2021-04-26 06:56 UTC, kraj requested changes
this does not compile as reported

2021-04-26 07:23 UTC, Silcet commented
Working on the fix atm. I'll push the changes in a bit

2021-04-27 05:32 UTC, Silcet commented
@kraj I've been working more with UFW these days and although it builds fine and has the proper python3 shebang to work now it has many other flaws. The configuration files are not read properly and other issues (I can elaborate if you are interested). I'm testing with a bumped version to 0.36 which seems to work much better. Would it make sense to just drop this PR and make another one with a working 0.36 instead?

2021-04-27 13:20 UTC, kraj commented
> @kraj I've been working more with UFW these days and although it builds fine and has the proper python3 shebang to work now it has many other flaws. The setup.py modifies source files in a way that is incompatible with how distutils is used in openembedded (I can elaborate if you are interested). I'm testing with a bumped version to 0.36 which seems to work much better. Would it make sense to just drop this PR and make another one with a working 0.36 instead?

that would be fine too

2021-05-02 17:37 UTC, kraj commented
applied with 5194af1afd

2021-05-02 17:37 UTC, closed without merging