Add flag to enable adbd service (#147)
openembedded/meta-openembedded pull request #399
Opened 2021-07-26 18:26 UTC by tewarid

android-tools-adbd service can be enabled in the image using  `USB_DEBUGGING_ENABLED = "1"` in `local.conf`.

2021-07-26 18:45 UTC, kraj commented
I wonder if it should be controlled via do_rootfs post-processing instead, so you can use same package to build with and without usb debugging

2021-07-26 19:03 UTC, tewarid commented
I did try it but I haven't been able to get do_rootfs post-processing to work with wic bmap image format used by meta-raspberrypi.

2021-08-05 15:13 UTC, kraj commented
Can you turn this into a PACKAGECONFIG that way someone can enable it via a bbappend.

2021-08-05 15:13 UTC, kraj requested changes
turn it into packageconfig or rootfs post processing cmd.

2021-08-05 18:16 UTC, tewarid commented
I'll close this PR and submit another later based on requested changes.

2021-08-05 18:16 UTC, closed without merging