fix SRCREV_FORMAT errors
openembedded/meta-openembedded pull request #442
Opened 2021-09-27 15:39 UTC by awe-1989

2021-09-27 15:46 UTC, akuster commented
the commits from awe-1989 are missing signed-off-by

2021-09-27 16:00 UTC, kraj requested changes

2021-09-27 16:00 UTC, kraj commented on meta-oe/recipes-graphics/spir/spirv-tools_git.bb
> +SRCREV_FORMAT ="ttols_headers_effcee_re2_googletest"
there is a typo s/ttools/spirv-tools/ and `headers` should be `spirv-headers`

2021-09-27 16:01 UTC, kraj commented on meta-networking/recipes-support/drbd/drbd-utils_9.12.0.bb
> +SRCREV_FORMAT = "utils_headers"
this should be drbd-utils_drbd-headers

2021-09-27 17:57 UTC, awe-1989 commented
Thanks for the comments. I pushed a new patch set.

2021-09-27 18:32 UTC, kraj approved these changes
this looks ok to me. I see that you proposed it for dunfell. I would like you to first ensure that all these changes are already present in one way or other in master branch as well. Then we can apply it for dunfell.

2021-09-27 19:13 UTC, awe-1989 commented
> this looks ok to me. I see that you proposed it for dunfell. I would like you to first ensure that all these changes are already present in one way or other in master branch as well. Then we can apply it for dunfell.

meta-networking/recipes-support/drbd/drbd-utils_9.12.0.bb was changed to drbd-utils_9.13.1.bb and fixed in bd499150d29a7c62d706f85ca5d879b2db772192

meta-oe/recipes-devtools/grpc/grpc_1.24.3.bb was changed to grpc_1.35.0.bb. during this time was switched to a single source. 15cff67fd6cdb34e3621368fe9ce94a98356f27a

meta-oe/recipes-graphics/spir/spirv-tools_git.bb was moved to openembedded-core with 8a5d7f28a02a18cd26749f7b97c1e85128fda720. There it has only one source in the master branch.

Thus, these problems should no longer occur in the master branch.

2021-11-02 13:09 UTC, akuster commented
pulled changes in for testing

2021-11-02 13:09 UTC, akuster commented
some of these also pulled in for hardknott

2021-11-16 13:38 UTC, akuster commented
merged
https://git.openembedded.org/meta-openembedded/commit/?h=dunfell&id=f8a2a7e41ac86371dd2b2b95c94d29c335f8676d

2021-11-16 13:38 UTC, akuster commented
thanks

2021-11-16 13:38 UTC, closed without merging