python3-prctl: Add https protocol to SRC_URI
openembedded/meta-openembedded pull request #490
Opened 2021-11-22 13:18 UTC by tewarid

GitHub has deprecated unencrypted git protocol

2021-12-08 19:18 UTC, kraj requested changes
Can you do a backport of 46c8e291352bfa513f46ce17b612cc5039e5b6e7 instead please ?

2021-12-09 09:59 UTC, tewarid commented
> Can you do a backport of [46c8e29](https://github.com/openembedded/meta-openembedded/commit/46c8e291352bfa513f46ce17b612cc5039e5b6e7) instead please ?

Done.

2022-01-29 14:05 UTC, akuster commented
in test branch

2022-02-08 21:01 UTC, kraj commented
applied with feab111e79eab2ed203e5affbc2b62b5aad03ef8

2022-02-08 21:01 UTC, closed without merging