usb-modeswitch: update 2.6.0 -> 2.6.1
openembedded/meta-openembedded pull request #659
Opened 2023-02-23 13:52 UTC by hoinmic

2023-02-23 15:56 UTC, kraj requested changes
Please add your `Signed-off-by` to the commit as well in v2

2023-02-23 15:56 UTC, kraj commented on meta-oe/recipes-support/usb-modeswitch/usb-modeswitch_2.6.1.bb
> +SRC_URI[md5sum] = "69d00d6ed7097b97d972a159d14cfba1"
drop `md5sum` we don't need it any longer.

2023-02-24 07:45 UTC, hoinmic commented
Modifications made. Thank you.

2023-02-28 01:44 UTC, kraj commented
This is now in master via 13606a7ed3

2023-02-28 01:44 UTC, closed without merging