meta-oe: fbida: switch to git and meson, update to newer SRC_REV
openembedded/meta-openembedded pull request #676
Opened 2023-04-11 09:36 UTC by rohieb

fbida has not seen any versioned releases for five years even though development has not stalled. Update to a recent version, switch to meson build, and make fbpdf build optional.

2023-04-11 17:04 UTC, kraj requested changes

2023-04-11 17:04 UTC, kraj commented on meta-oe/recipes-graphics/fbida/files/0002-meson.build-add-features-options-for-png-gif-tiff-we.patch
> +
follow https://www.openembedded.org/wiki/Commit_Patch_Message_Guidelines#Patch_Header_Recommendations:_Upstream-Status

2023-04-11 21:52 UTC, kraj commented
it fails to build for musl targets see [1]

```
../git/gfx.h:43:5: error: unknown type name 'dev_t'; did you mean 'div_t'?
    dev_t devnum;
    ^~~~~
    div_t
TOPDIR/build/tmp/work/cortexa57-yoe-linux-musl/fbida/2.14+gitAUTOINC+eb769e3d7f-r0/recipe-sysroot/usr/include/stdlib.h:64:35: note: 'div_t' declared here
typedef struct { int quot, rem; } div_t;
                                  ^
1 error generated
```

I think we need to add `#include <sys/types.h>` in `gfx.h` to fix it.

[1] https://errors.yoctoproject.org/Errors/Details/699643/

2023-07-10 02:28 UTC, kraj commented
I have addressed the comments as needed and accepted this change at 28b86939d5 on master branch

2023-07-10 02:28 UTC, closed without merging

2023-07-15 15:51 UTC, rohieb commented
Thank you, sorry it fell through the cracks on my side…