tmux: Upgrade to 3.4
openembedded/meta-openembedded pull request #872
Opened 2024-09-13 17:52 UTC by rtollert

Changes vs 3.3a are located at
https://raw.githubusercontent.com/tmux/tmux/3.4/CHANGES. However, the most pressing reason to upgrade is that tmux crashes on copy, see https://github.com/tmux/tmux/issues/3699. Reproduced in scarthgap.

tmux's config parser was rewritten to use yacc, which necessitates DEPENDS += bison-native.

2024-09-13 18:32 UTC, kraj requested changes

2024-09-13 18:32 UTC, kraj commented on meta-oe/recipes-extended/tmux/tmux_3.4.bb
> +SRC_URI[md5sum] = "f6e35f957f91af5bb07cb8449228f5cd"
drop `md5sum` they are deprecated.

2024-09-13 18:45 UTC, rtollert commented on meta-oe/recipes-extended/tmux/tmux_3.4.bb
> +SRC_URI[md5sum] = "f6e35f957f91af5bb07cb8449228f5cd"
👍🏻 ?

2024-09-15 14:47 UTC, kraj commented
applied with 9356340655

2024-09-15 14:47 UTC, closed without merging