Bump nbdit to the newest repo tag
openembedded/meta-openembedded pull request #899
Opened 2024-11-14 09:29 UTC by MarcinDigitic

Recently, the official nbdkit repo has been changed: from https://github.com/libguestfs/nbdkit
into https://gitlab.com/nbdkit/nbdkit

Additionally, the newest tag versiion is v1.41.8.
The patch used with version 1.33.11 is also merged to v1.41.8, so it is obsolete now.

This commit bumps the used version from 1.33.11 to 1.41.8.

It was tested with one of openbmc images.

2024-11-20 01:03 UTC, kraj requested changes
this bump results in some TMPDIR leaking into binaries

```
stdio: ERROR: nbdkit-1.41.8-r0 do_package_qa: QA Issue: File /usr/lib/nbdkit/plugins/nbdkit-cc-plugin.so in package nbdkit contains reference to TMPDIR [buildpaths]
stdio: ERROR: nbdkit-1.41.8-r0 do_package_qa: Fatal QA errors were found, failing task.
```

Please find and fix them

2024-11-21 08:28 UTC, MarcinDigitic commented
Hi @kraj ,

Could you provide more details on how did you encounter this error?
This is my first PR for this repo and I am not sure, which tests should be run and on which platform.
I have tested this change only with openbmc repo and one of the machines, which uses nbdkit directly and there was no such issue.

Kind regards,
Marcin

> this bump results in some TMPDIR leaking into binaries
> 
> ```
> stdio: ERROR: nbdkit-1.41.8-r0 do_package_qa: QA Issue: File /usr/lib/nbdkit/plugins/nbdkit-cc-plugin.so in package nbdkit contains reference to TMPDIR [buildpaths]
> stdio: ERROR: nbdkit-1.41.8-r0 do_package_qa: Fatal QA errors were found, failing task.
> ```
> 
> Please find and fix them

2024-11-21 09:11 UTC, kraj commented
> Hi @kraj ,
> 
> Could you provide more details on how did you encounter this error? This is my first PR for this repo and I am not sure, which tests should be run and on which platform. I have tested this change only with openbmc repo and one of the machines, which uses nbdkit directly and there was no such issue.
> 
> Kind regards, Marcin
> 
> > this bump results in some TMPDIR leaking into binaries
> > ```
> > stdio: ERROR: nbdkit-1.41.8-r0 do_package_qa: QA Issue: File /usr/lib/nbdkit/plugins/nbdkit-cc-plugin.so in package nbdkit contains reference to TMPDIR [buildpaths]
> > stdio: ERROR: nbdkit-1.41.8-r0 do_package_qa: Fatal QA errors were found, failing task.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Please find and fix them

I built it using vanilla poky for qemux86-64 distro and adding meta-openembedded layers added.

2024-11-27 10:02 UTC, MarcinDigitic commented
Hi @kraj ,
I fixed the issue with TMPDIR using your patch.
However, I see here two potential issues:
1. In the newest nbdkit code there is a change, where variables CC_PLUGIN_CC and CC_PLUGIN_CFLAGS were introduced.
I suspect that this could allow to define those variables in bb file directly, instead of using the patch. For now, I do not have any idea how to setup them properly in bb file to prevent the issue with TMPDIR.
2. I noticed that this patch does not work properly if build is performed when using devtool modify and any other source folder. I suspect that this was behind the intention of introducing CC_PLUGIN variables.

2024-11-27 17:55 UTC, kraj commented
> Hi @kraj , I fixed the issue with TMPDIR using your patch. However, I see here two potential issues:
> 
> 1. In the newest nbdkit code there is a change, where variables CC_PLUGIN_CC and CC_PLUGIN_CFLAGS were introduced.
>    I suspect that this could allow to define those variables in bb file directly, instead of using the patch. For now, I do not have any idea how to setup them properly in bb file to prevent the issue with TMPDIR.
> 2. I noticed that this patch does not work properly if build is performed when using devtool modify and any other source folder. I suspect that this was behind the intention of introducing CC_PLUGIN variables.

yeah, if you look at the patch its assuming workdir = abs_top_builddir which may alter when doing builds with devtool.
devtool is to be used during development so not as big an issue but it would be good to build consistently with or without externalsrc that devtool uses.

2024-11-29 02:45 UTC, kraj commented
applied with 262bab29e5

2024-11-29 02:45 UTC, closed without merging